services:
  db:
    image: postgres:16-alpine
    container_name: votacao-db
    environment:
      POSTGRES_DB: votacao
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - votacao_pgdata:/var/lib/postgresql/data

volumes:
  votacao_pgdata:
